title: ddvv-blog
description: "ddvvmmzz"
author:
  name: "ddvv"
  email: "dadavivi512@gmail.com"
  url: "ddvvmmzz.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/
excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ddvv"
year : "2019"